### ISSUE TITLE
Error: Transducer is cyclic

### ISSUE THREAD

**Issue by dasharakelova** [dasharakelova/abaza_analyzer#2]
I get this error when trying to apply fst2strings: 

hfst-fst2strings: Transducer is cyclic. Use one or more of these options: -n, -N, -r, -l, -L, -c

But I don't know what went wrong.

**Comment by nlhowell** [comment]
The cycle comes from `0:ы` in the twol alphabet; this says that
surface forms can contain unlimited numbers of `ы`, and they can go
anywhere.  (Hence the cycle!)

When I remove this and recompile, fst2strings stops complaining. But
maybe it was modeling an important effect? If so, some rules need to
be added to limit how many `ы` can be inserted...
